# Generated by Django 5.0 on 2024-01-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_laptop_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lap',
            name='slug',
            field=models.SlugField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
